### ISSUE TITLE
Retrospective looking back on first 6 sessions (23 March 2020 1300-1500 BST)

### ISSUE THREAD

**Issue by katjam** [neontribe/code-reading-club#2]
Agenda TBC
- What worked well code & exercises
- What didn't work well
- Idea for different ideas

Objective TBC
- A set of code exercises with facilitation guidelines
- A set of guidelines for finding & choosing code for sessions
- Some thinking about how to make this repo more usable for other groups to run clubs on their own

**Comment by AlinChindea** [comment]
I am not 100% sure that I can join the call at least not from the beginning. so here is some feedback. 

- clarify the goal/objective - is it to learn a new programming language? is it to be a better programmer? - make it a S.M.A.R.T. one.
- whatever the goal, I think it's better to stick to one programming language - learning about design or architecture of different languages can be advantageous but if you are not working with those and every week is a new language I am not sure how this is helpful. I think one language can also be more useful towards measuring to what extent we achieved our goal
- to make the repo more usable - consider making it a template and prospective users/clubs can be able to use it immediately to generate new repositories with all of the template repository’s files and folders. [See here for details](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)
- consider more homogenous groups in terms of experience - not necessarily same level but not sure how useful it is to have newbies with very experienced programmers. At times I felt foreign to the whole experience as the more seasoned participants were stealing the show (my perception so very subjective) and didn't understand what they were discussing. 

I'll try to join in but definitely not from the beginning. Hope these help.

**Comment by katjam** [comment]
@katjam To add some notes from session and post video to Rupert and Felienne

**Comment by katjam** [comment]
General thoughts/ comments from retrospective session:

Good
- the sessions are useful for learning to code
- approaching code in this way makes it less intimidating

Neutral
- people approach the colouring exercise differently (some scanning code, so reading more deeply etc)

Bad
- there is time pressure in the sessions

**Comment by katjam** [comment]
- [ ] Write up Katja's notes
- [ ] Write up Dan's notes 
- [ ] Make clear next step actions in the issues arisen

then close.

**Comment by katjam** [comment]
Closing as been written up and ding next steps
