### ISSUE TITLE
Could we share some examples of scribbled on code?

### ISSUE THREAD

**Issue by Felienne** [neontribe/code-reading-club#9]
Did we save them? Would ppl be ok with us sharing them here? I think @marxian had some sort of nice collab tool but I do not remember what it was.

**Comment by marxian** [comment]
@Felienne I've sent you a link to the board privately. I've removed names and you can feel free to use what's there.

I'll try to start uploading examples here in due course.

**Comment by Felienne** [comment]
Thanks!
